// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressUsers struct {
	Addressid int    `json:"addressid"`
	Userid    int    `json:"userid"`
	Address   string `json:"address"`
	Status    bool   `json:"status"`
}

type NewStore struct {
	Storename    string `json:"storename"`
	Storeaddress string `json:"storeaddress"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Order struct {
	Orderid         int    `json:"orderid"`
	Billingid       string `json:"billingid"`
	User            *User  `json:"user"`
	Transactiondate string `json:"transactiondate"`
	Status          string `json:"status"`
}

type OrderDetails struct {
	Orderdetailid int      `json:"orderdetailid"`
	Billingid     string   `json:"billingid"`
	Product       *Product `json:"product"`
	Totalproduct  int      `json:"totalproduct"`
	Createat      string   `json:"createat"`
}

type Product struct {
	Productid          int     `json:"productid"`
	Store              *Store  `json:"store"`
	Productname        string  `json:"productname"`
	Productdescription *string `json:"productdescription"`
	Price              float64 `json:"price"`
	Stock              int     `json:"stock"`
	Createat           string  `json:"createat"`
}

type Store struct {
	Storeid      int    `json:"storeid"`
	Storename    string `json:"storename"`
	Storeaddress string `json:"storeaddress"`
	Createat     string `json:"createat"`
}

type Todo struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	Userid   int           `json:"userid"`
	Name     string        `json:"name"`
	Createat string        `json:"createat"`
	Address  *AddressUsers `json:"address"`
	Status   bool          `json:"status"`
}
